### ISSUE TITLE
XOR example, evolve-spiking.py is not working.

### ISSUE THREAD

**Issue by evolvingfridge** [CodeReclaimers/neat-python#38]
Testing master branch, almost all examples are working on python 2.7.12, so far only issue with evole-spiking.  First error I got was:  <TypeError: eval_fitness() takes exactly 1 argument (2 given)> . Tried to hack it :) by adding argument to eval_func and got error:  <AttributeError: 'tuple' object has no attribute 'node_genes'> 
I am trying to fix it, but so far all seems very painfully complicated, any tips on how to fix it or eta for a fix ?

**Comment by CodeReclaimers** [comment]
Yep, I still need to update the Izhikevitch genome implementation to work with the current framework. :)  I'm hoping I can get to that over the weekend.

Thanks for testing with 2.7!  I've been working in 3.5 for development, so it's good to know things aren't too bad in 2.x.

**Comment by abrahamrhoffman** [comment]
Using 2.7.12 myself. Let me know if I can help somehow. I'd be happy to aid in the overhaul effort.

**Comment by CodeReclaimers** [comment]
Just an update: the spiking example now runs, but doesn't seem to really ever make any progress towards a solution.  I'm guessing there's probably something wrong with the neuron or network implementation.

**Comment by d0pa** [comment]
Thank you, it will make much easier to figure out whats not working, if have time next will will dedicate some time for spiking, I find spiking are most interesting neural model.
